<a href="https://colab.research.google.com/github/AI-ClassWork/Next_Word_Prediction/blob/main/Next_Word_Prediction_ICS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!python -m spacy download en_core_web_md

In [ ]:
#import spacy

In [ ]:
#embedding_file=spacy.load('en_core_web_md')

In [ ]:
#embedding_file('want').vector.shape

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize,sent_tokenize
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
#!pip install nlp

In [ ]:
#from nlp import load_dataset
from nltk.tokenize import word_tokenize,sent_tokenize

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
import nltk
import math
import json
import tensorflow_hub as hub
import spacy

In [ ]:
nltk.download('punkt')
nltk.download('gutenberg')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.


True

In [ ]:
from tensorflow.keras.layers import SimpleRNN,GRU,LSTM,Dense,Embedding,InputLayer,Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import CategoricalCrossentropy
from tensorflow.keras.losses import CategoricalCrossentropy,categorical_crossentropy
from tensorflow.keras import Model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
#from nltk.corpus import gutenberg

In [ ]:
DIM=10

In [ ]:
data=open("0001a.txt")
data=data.read()

In [ ]:
data

"Racism is still a problem within our society today, and many ethnic minorities face inequalities in many areas, including education, housing, and employment. Ethnic minorities are concentrated into certain areas of the job market, such as manufacture and communication (Brown, 1992), are most likely to be the victims of assault (Abercrombie et al, 1994), and recent surveys have shown that racist ideas still exist in society. This can be seen in a survey, carried out in 1993, that asked a white sample whether they agreed or disagreed with the statement: 'Immigration has enriched the quality of life in Britain' and nearly half of the sample disagreed (Abercrombie et al, 1994, p255). In this essay I will look at what racism is, and how it is defined in contemporary society, and I will then explore why it still persists. In this section I will cover three areas that I think have contributed to the continued existence of racism; culture, economy and politics, all of which have meant that ra

In [ ]:
corpus_list=[]
corpus=sent_tokenize(data)
for sent in corpus:
  corpus_list.append([sent])

In [ ]:
corpus_list

[['Racism is still a problem within our society today, and many ethnic minorities face inequalities in many areas, including education, housing, and employment.'],
 ['Ethnic minorities are concentrated into certain areas of the job market, such as manufacture and communication (Brown, 1992), are most likely to be the victims of assault (Abercrombie et al, 1994), and recent surveys have shown that racist ideas still exist in society.'],
 ["This can be seen in a survey, carried out in 1993, that asked a white sample whether they agreed or disagreed with the statement: 'Immigration has enriched the quality of life in Britain' and nearly half of the sample disagreed (Abercrombie et al, 1994, p255)."],
 ['In this essay I will look at what racism is, and how it is defined in contemporary society, and I will then explore why it still persists.'],
 ['In this section I will cover three areas that I think have contributed to the continued existence of racism; culture, economy and politics, all o

In [ ]:
len(corpus_list)

48

In [ ]:
vectorizer = TfidfVectorizer()

In [ ]:
X = vectorizer.fit_transform(corpus)

In [ ]:
X.shape

(48, 459)

In [ ]:
vocab=vectorizer.get_feature_names_out()

In [ ]:
vocab

array(['1950s', '1960s', '1962', '1968', '1970s', '1978', '1979', '1987',
       '1989', '1992', '1993', '1994', '1999', '2004', 'abercrombie',
       'abilities', 'abnormal', 'according', 'acknowledges', 'act',
       'action', 'actions', 'after', 'again', 'agreed', 'al', 'all',
       'along', 'also', 'although', 'an', 'and', 'apparent', 'are',
       'areas', 'argue', 'argued', 'argues', 'army', 'around', 'as',
       'asked', 'assault', 'associated', 'asylum', 'at', 'automatically',
       'banton', 'barbaric', 'be', 'been', 'before', 'began', 'behaviour',
       'belief', 'beliefs', 'between', 'black', 'both', 'bought',
       'britain', 'british', 'broader', 'brown', 'but', 'by', 'can',
       'cannibalism', 'capitalism', 'capitalist', 'capitalists',
       'carmichael', 'carried', 'cases', 'castles', 'categorisation',
       'categorises', 'causing', 'century', 'certain', 'changed',
       'changing', 'characteristics', 'cited', 'civilisation', 'clamp',
       'closely', 'coloni

In [ ]:
len(vocab)

459

In [ ]:
embeddings_array=X.toarray().T

In [ ]:
vocab[458]

'your'

In [ ]:
embeddings_array[458]

array([0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.1971123,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ])

In [ ]:
pca=PCA(n_components=DIM)

In [ ]:
dense_embeddings=pca.fit_transform(embeddings_array)

In [ ]:
dense_embeddings[458]

array([-0.04527489, -0.0150985 ,  0.04461296, -0.01386764, -0.01425557,
       -0.0073273 , -0.01786573, -0.02991515,  0.00897281,  0.01337461])

In [ ]:
embeddings_dict={}

In [ ]:
for i in range(len(vocab)):
  embeddings_dict[vocab[i]]=dense_embeddings[i].tolist()

In [ ]:
embeddings_dict

{'1950s': [0.007491281959999963,
  -0.06961875607006808,
  -0.06313641765906514,
  -0.06986373050868105,
  -0.07213131275582167,
  0.02149137243193447,
  0.028061861988931132,
  0.06832807922888219,
  0.0448506725745445,
  -0.013894700828414477],
 '1960s': [-0.039366365474956706,
  -0.026985902573559317,
  -0.06677900319792225,
  -0.018769304759848175,
  -0.04561202309426524,
  -0.001187179558523686,
  0.05203498043835848,
  0.03884081777321361,
  -0.026765238971463108,
  0.011102638874778643],
 '1962': [-0.03936636547495723,
  -0.02698590257355908,
  -0.06677900319792196,
  -0.018769304759847623,
  -0.045612023094265035,
  -0.001187179558523525,
  0.05203498043835787,
  0.03884081777321356,
  -0.026765238971463084,
  0.011102638874778402],
 '1968': [-0.04922149989081426,
  -0.0007428325482989652,
  -0.017468124432266367,
  0.010313900897218531,
  0.0017132499045658192,
  -0.024883993395677678,
  -0.00632749335712379,
  -0.00483139064556558,
  -0.02057427676028852,
  0.0088238908230857

In [ ]:
seq_len=10
tokenizer=Tokenizer()
tokenizer.fit_on_texts([data])
x=tokenizer.texts_to_sequences([data])
x

[[8,
  10,
  17,
  7,
  69,
  90,
  53,
  11,
  49,
  2,
  54,
  41,
  42,
  218,
  219,
  4,
  54,
  70,
  136,
  220,
  137,
  2,
  221,
  41,
  42,
  12,
  222,
  55,
  91,
  70,
  3,
  1,
  223,
  71,
  138,
  6,
  224,
  2,
  225,
  92,
  93,
  12,
  226,
  227,
  9,
  24,
  1,
  228,
  3,
  229,
  139,
  140,
  141,
  142,
  2,
  230,
  231,
  22,
  232,
  5,
  33,
  14,
  17,
  143,
  4,
  11,
  13,
  50,
  24,
  72,
  4,
  7,
  233,
  144,
  73,
  4,
  234,
  5,
  235,
  7,
  34,
  145,
  236,
  25,
  237,
  146,
  147,
  18,
  1,
  238,
  239,
  27,
  240,
  1,
  241,
  3,
  242,
  4,
  243,
  2,
  244,
  245,
  3,
  1,
  145,
  147,
  139,
  140,
  141,
  142,
  246,
  4,
  13,
  148,
  35,
  43,
  149,
  44,
  150,
  8,
  10,
  2,
  247,
  15,
  10,
  94,
  4,
  56,
  11,
  2,
  35,
  43,
  151,
  248,
  74,
  15,
  17,
  75,
  4,
  13,
  249,
  35,
  43,
  250,
  152,
  70,
  5,
  35,
  251,
  22,
  252,
  9,
  1,
  153,
  253,
  3,
  8,
  57,
  58,
  2,
  95,
  154,
  3,
 

In [ ]:
x[0]

[8,
 10,
 17,
 7,
 69,
 90,
 53,
 11,
 49,
 2,
 54,
 41,
 42,
 218,
 219,
 4,
 54,
 70,
 136,
 220,
 137,
 2,
 221,
 41,
 42,
 12,
 222,
 55,
 91,
 70,
 3,
 1,
 223,
 71,
 138,
 6,
 224,
 2,
 225,
 92,
 93,
 12,
 226,
 227,
 9,
 24,
 1,
 228,
 3,
 229,
 139,
 140,
 141,
 142,
 2,
 230,
 231,
 22,
 232,
 5,
 33,
 14,
 17,
 143,
 4,
 11,
 13,
 50,
 24,
 72,
 4,
 7,
 233,
 144,
 73,
 4,
 234,
 5,
 235,
 7,
 34,
 145,
 236,
 25,
 237,
 146,
 147,
 18,
 1,
 238,
 239,
 27,
 240,
 1,
 241,
 3,
 242,
 4,
 243,
 2,
 244,
 245,
 3,
 1,
 145,
 147,
 139,
 140,
 141,
 142,
 246,
 4,
 13,
 148,
 35,
 43,
 149,
 44,
 150,
 8,
 10,
 2,
 247,
 15,
 10,
 94,
 4,
 56,
 11,
 2,
 35,
 43,
 151,
 248,
 74,
 15,
 17,
 75,
 4,
 13,
 249,
 35,
 43,
 250,
 152,
 70,
 5,
 35,
 251,
 22,
 252,
 9,
 1,
 153,
 253,
 3,
 8,
 57,
 58,
 2,
 95,
 154,
 3,
 45,
 22,
 254,
 5,
 8,
 10,
 46,
 155,
 2,
 255,
 76,
 3,
 53,
 11,
 51,
 35,
 43,
 47,
 24,
 256,
 44,
 257,
 146,
 258,
 259,
 3,
 8,
 260,
 261,
 7,
 262,
 156,

In [ ]:
len(x[0])

1555

In [ ]:
tokenizer.get_config()

In [ ]:
vocab_dict=json.loads(tokenizer.get_config().get('word_index'))

In [ ]:
vocab_dict

In [ ]:
vals=list(vocab_dict.values())
keys=list(vocab_dict.keys())
keys[vals.index(1)]

In [ ]:
vocab_size=len(keys)

In [ ]:
vocab_size

469

In [ ]:
embedding_array=np.zeros((vocab_size+1,DIM))
embedding_array.shape

(470, 10)

In [ ]:
for word,i in tokenizer.word_index.items():
  if word in embeddings_dict:
    embedding_vector=embeddings_dict[word]
  if embedding_vector is not None:
    embedding_array[i]=embedding_vector

In [ ]:
"""for word,i in tokenizer.word_index.items():
  embedding_vector=embedding_file(word).vector
  if embedding_vector is not None:
    embedding_array[i]=embedding_vector"""

'for word,i in tokenizer.word_index.items():\n  embedding_vector=embedding_file(word).vector\n  if embedding_vector is not None:\n    embedding_array[i]=embedding_vector'

In [ ]:
#embedding_array[7306]

In [ ]:
len(x[0])

1555

In [ ]:
x[0][0:15]

[8, 10, 17, 7, 69, 90, 53, 11, 49, 2, 54, 41, 42, 218, 219]

In [ ]:
inner_list=[]
X={}
corpus_length=len(x[0])-seq_len
k=0

for i in range(0,corpus_length,seq_len):
  inner_list.clear()
  for j in range(i,i+seq_len):
    inner_list.append(x[0][j])
  X[k]=inner_list[:]
  k=k+1

In [ ]:
#list(X.values())
x_train=[]
y_train=[]
for it in list(X.values()):
  x_train.append(it[0:-1])
  y_train.append(it[-1])

In [ ]:
x_train[3]

[3, 1, 223, 71, 138, 6, 224, 2, 225]

In [ ]:
len(x_train)

155

In [ ]:
X=np.array(x_train)
#input_seq.shape
y=np.array(y_train).reshape(len(y_train),1)
#target=tf.reshape(tf.constant(y_train),[len(y_train),1])

In [ ]:
y.shape

(155, 1)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [ ]:
X_train.shape

(108, 9)

In [ ]:
y_train

In [ ]:
input_seq,test_seq,y_true,y_hat=tf.constant(X_train),tf.constant(X_test),tf.constant(y_train),tf.constant(y_test)

In [ ]:
input_seq

In [ ]:
y_true

In [ ]:
tf.reduce_max(input_seq)+1

<tf.Tensor: shape=(), dtype=int64, numpy=469>

In [ ]:
input=Input(shape=(seq_len-1,))
x=Embedding(input_dim=vocab_size+1,input_length=seq_len-1,output_dim=20,trainable=True)(input)
x=LSTM(256,return_sequences=True)(x)
x=LSTM(128,return_sequences=True)(x)
x=LSTM(64)(x)
x=Dense(32)(x)
output=Dense(vocab_size,activation="softmax")(x)
model=Model(input,output)

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 9)]               0         
                                                                 
 embedding (Embedding)       (None, 9, 20)             9400      
                                                                 
 lstm (LSTM)                 (None, 9, 256)            283648    
                                                                 
 lstm_1 (LSTM)               (None, 9, 128)            197120    
                                                                 
 lstm_2 (LSTM)               (None, 64)                49408     
                                                                 
 dense (Dense)               (None, 32)                2080      
                                                                 
 dense_1 (Dense)             (None, 469)               15477 

In [ ]:
model.compile(optimizer=Adam(0.01),loss=tf.keras.losses.sparse_categorical_crossentropy,metrics=['accuracy'])

In [ ]:
model.fit(input_seq,y_true,epochs=10)

Epoch 1/10
4/4 [==============================] - 9s 18ms/step - loss: 6.1245 - accuracy: 0.0093
Epoch 2/10
4/4 [==============================] - 0s 16ms/step - loss: 5.2877 - accuracy: 0.0556
Epoch 3/10
4/4 [==============================] - 0s 22ms/step - loss: 4.5388 - accuracy: 0.0648
Epoch 4/10
4/4 [==============================] - 0s 17ms/step - loss: 4.2994 - accuracy: 0.0370
Epoch 5/10
4/4 [==============================] - 0s 16ms/step - loss: 4.2583 - accuracy: 0.0278
Epoch 6/10
4/4 [==============================] - 0s 18ms/step - loss: 4.2158 - accuracy: 0.0463
Epoch 7/10
4/4 [==============================] - 0s 18ms/step - loss: 4.2067 - accuracy: 0.0556
Epoch 8/10
4/4 [==============================] - 0s 17ms/step - loss: 4.2023 - accuracy: 0.0370
Epoch 9/10
4/4 [==============================] - 0s 17ms/step - loss: 4.1935 - accuracy: 0.0463
Epoch 10/10
4/4 [==============================] - 0s 18ms/step - loss: 4.1831 - accuracy: 0.0556


In [ ]:
model.evaluate(test_seq,y_hat)

2/2 [==============================] - 1s 13ms/step - loss: 7.7811 - accuracy: 0.0426


[7.781139850616455, 0.042553190141916275]

In [ ]:
input_text=["she was such a good person"]
#input_text=["he was such a good person and honestly speaking he did make good use of his"]
#input_text=["can you please"]
#input_text=["marriage is such a beautiful"]
toks=tokenizer.texts_to_sequences(input_text)
ins=pad_sequences(toks,maxlen=seq_len-1)
input_tensor=tf.constant(ins)
input_tensor

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[  0,   0,   0,   0,   0,   0,  26, 138,   7]], dtype=int32)>

In [ ]:
pred=model.predict(input_tensor)
keys[vals.index(np.argmax(pred))]

'that'

In [ ]:
input_text[0]=input_text[0]+' '+keys[vals.index(np.argmax(pred))]
input_text[0]

'she was such a good person that'

In [ ]:
for i in range(10):
  toks=tokenizer.texts_to_sequences(input_text)
  ins=pad_sequences(toks,maxlen=seq_len-1)
  input_tensor=tf.constant(ins)
  pred=model.predict(input_tensor)
  input_text[0]=input_text[0]+' '+keys[vals.index(np.argmax(pred))]

print(input_text)

['she was such a good person that that that that that that that that that that that']


In [ ]:
sort_pred=np.argsort(pred[0])
pred_words=np.flip(sort_pred[-20:])
for index in pred_words:
  print(keys[vals.index(index)])

that
racism
and
the
non
a
idea
to
been
still
other
jobs
ideas
these
society
work
an
societies
with
threat
